### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by wallnera** [rstropek-teaching/contact-list-quiz-5ahif-wallnera#1]
http://contactlistswaggerwallner22112017.azurewebsites.net/contacts

**Comment by rstropek** [comment]
@wallnera Thank you for your homework. You did not implement the Swagger spec 100%, but you nearly made it 👍 Your extra point is secured.

I took a look at your code and found two major possibilities for enhancements:

* You store data in `ContactController.items`. It is a `static` member. However, you add demo data in `ContactController`'s constructor. Therefore, every request adds more demo data. You should add demo data in a *static constructor* instead.

* Don't forget to use Linq ([example](https://github.com/rstropek-teaching/contact-list-quiz-5ahif-wallnera/blob/a405e9af7b2fd6c27853eaed4cd003b3a32ce049/ContactListSwagger/ContactListSwagger/ContactsController.cs#L69))

Greetings,
Rainer Stropek.
